name: hello-world
on: push
jobs:
  my-job:
    runs-on: macos-13
    steps:
      - name: my-step1
        run: echo "Hello World Manick1!"
      - name: my-step2
        run: echo "Hello World Manick2!"

